# Adapted from https://github.com/ChrisPenner/haskell-stack-travis-ci
language: minimal
sudo: true

cache:
    directories:
        - $HOME/.ghc
        - $HOME/.cabal
        - $HOME/.stack
        - .stack-work

matrix:
  fast_finish: true
  include:
    # Add build targets here
    - env: CACHE_NAME=linux BUILD_BINARY=1
      compiler: ": #stack 8.4.4"
    - env: CACHE_NAME=osx BUILD_BINARY=1
           LDFLAGS=-L/usr/local/opt/readline/lib CFLAGS=-I/usr/local/opt/readline/include
           EXTRA_INCLUDE_DIRS=/usr/local/opt/readline/include
           EXTRA_LIB_DIRS=/usr/local/opt/readline/lib
      compiler: ": #stack 8.4.4"
      os: osx

install:
 - unset CC
 - export PATH=$HOME/.local/bin:$PATH
 - ./.travis/install-ghr.sh
 - ./.travis/install-stack.sh

script:
 - echo "$(stack ghc -- --version) [$(stack ghc -- --print-project-git-commit-id 2> /dev/null || echo '?')]"
 - GHC_OPTIONS="-Werror"
 - set -ex
 - stack exec -- ghc-pkg unregister readline || true
 - stack install readline
     --extra-include-dirs=$EXTRA_INCLUDE_DIRS
     --extra-lib-dirs=$EXTRA_LIB_DIRS
   # Run tests
   #stack --no-terminal test --ghc-options="$GHC_OPTIONS"
 - set +ex

after_success:
 - |
   # Build and ship binary
   export BUILD_BINARY=true
   export TRAVIS_TAG=$(git rev-parse HEAD)
   ./.travis/attach-binary.sh

notifications:
  email: false
