resolver: lts-12.16

packages:
- '.'

extra-deps:
- ghci-pretty-0.0.2
- HSH-2.1.3
- ipprint-0.6
- restless-git-0.7
- rosezipper-0.2
- sr-extra-1.46.3.2
- temporary-1.2.1.1
- tree-view-0.5
- s-cargot-0.1.4.0
- Unixutils-1.54.1
- readline-1.0.3.0
- hevm-0.21
- multiset-0.3.4.1
- text-format-0.3.2

nix:
  packages:
  - bzip2
  - readline
  - zlib
  - ncurses
  - secp256k1
